"""empty message

Revision ID: fc27f1f9af0e
Revises: 
Create Date: 2023-12-22 17:48:55.382409

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fc27f1f9af0e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('link', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('date', sa.Text(), nullable=False),
    sa.Column('snippet', sa.Text(), nullable=False),
    sa.Column('thumbnail', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dvadmin_tasks', schema=None) as batch_op:
        batch_op.drop_index('dvadmin_tasks_creator_id_0c2ca68f')
        batch_op.drop_index('dvadmin_tasks_is_deleted_acdeefcb')
        batch_op.drop_index('keyword_id')

    op.drop_table('dvadmin_tasks')
    with op.batch_alter_table('dvadmin_keywords', schema=None) as batch_op:
        batch_op.drop_index('dvadmin_keywords_creator_id_78641082')
        batch_op.drop_index('dvadmin_keywords_is_deleted_75748605')

    op.drop_table('dvadmin_keywords')
    with op.batch_alter_table('dvadmin_system_post', schema=None) as batch_op:
        batch_op.drop_index('dvadmin_system_post_creator_id_b5ef9351')

    op.drop_table('dvadmin_system_post')
    with op.batch_alter_table('dvadmin_system_dept', schema=None) as batch_op:
        batch_op.drop_index('dvadmin_system_dept_creator_id_e69fd1ae')
        batch_op.drop_index('dvadmin_system_dept_parent_id_0f9eb419')
        batch_op.drop_index('key')

    op.drop_table('dvadmin_system_dept')
    with op.batch_alter_table('dvadmin_system_users_groups', schema=None) as batch_op:
        batch_op.drop_index('dvadmin_system_users_groups_users_id_group_id_7460f482_uniq')

    op.drop_table('dvadmin_system_users_groups')
    with op.batch_alter_table('dvadmin_system_role_permission', schema=None) as batch_op:
        batch_op.drop_index('dvadmin_system_role_perm_role_id_menubutton_id_46c1e3ca_uniq')
        batch_op.drop_index('dvadmin_system_role_permission_menubutton_id_7ba32ee0')
        batch_op.drop_index('dvadmin_system_role_permission_role_id_bf988ad5')

    op.drop_table('dvadmin_system_role_permission')
    with op.batch_alter_table('django_celery_beat_solarschedule', schema=None) as batch_op:
        batch_op.drop_index('django_celery_beat_solar_event_latitude_longitude_ba64999a_uniq')

    op.drop_table('django_celery_beat_solarschedule')
    with op.batch_alter_table('dvadmin_task_result', schema=None) as batch_op:
        batch_op.drop_index('dvadmin_task_result_creator_id_f7f8b173')
        batch_op.drop_index('dvadmin_task_result_is_deleted_af5ad10e')

    op.drop_table('dvadmin_task_result')
    op.drop_table('article')
    with op.batch_alter_table('dvadmin_system_users_role', schema=None) as batch_op:
        batch_op.drop_index('dvadmin_system_users_role_role_id_e37d9591')
        batch_op.drop_index('dvadmin_system_users_role_users_id_a25207bc')
        batch_op.drop_index('dvadmin_system_users_role_users_id_role_id_02908e92_uniq')

    op.drop_table('dvadmin_system_users_role')
    with op.batch_alter_table('captcha_captchastore', schema=None) as batch_op:
        batch_op.drop_index('hashkey')

    op.drop_table('captcha_captchastore')
    with op.batch_alter_table('dvadmin_system_login_log', schema=None) as batch_op:
        batch_op.drop_index('dvadmin_system_login_log_creator_id_5f6dc165')

    op.drop_table('dvadmin_system_login_log')
    with op.batch_alter_table('dvadmin_message_center_target_user', schema=None) as batch_op:
        batch_op.drop_index('dvadmin_message_center_target_user_creator_id_0a27a561')
        batch_op.drop_index('dvadmin_message_center_target_user_messagecenter_id_54f35bf8')
        batch_op.drop_index('dvadmin_message_center_target_user_users_id_9ff81ff5')

    op.drop_table('dvadmin_message_center_target_user')
    op.drop_table('django_celery_beat_intervalschedule')
    with op.batch_alter_table('django_celery_results_groupresult', schema=None) as batch_op:
        batch_op.drop_index('django_cele_date_cr_bd6c1d_idx')
        batch_op.drop_index('django_cele_date_do_caae0e_idx')
        batch_op.drop_index('group_id')

    op.drop_table('django_celery_results_groupresult')
    with op.batch_alter_table('django_content_type', schema=None) as batch_op:
        batch_op.drop_index('django_content_type_app_label_model_76bd3d3b_uniq')

    op.drop_table('django_content_type')
    op.drop_table('django_celery_beat_crontabschedule')
    with op.batch_alter_table('dvadmin_message_center_target_dept', schema=None) as batch_op:
        batch_op.drop_index('dvadmin_message_center_t_messagecenter_id_dept_id_d9fb0c77_uniq')
        batch_op.drop_index('dvadmin_message_center_target_dept_dept_id_616decc4')
        batch_op.drop_index('dvadmin_message_center_target_dept_messagecenter_id_69868c17')

    op.drop_table('dvadmin_message_center_target_dept')
    with op.batch_alter_table('django_celery_results_chordcounter', schema=None) as batch_op:
        batch_op.drop_index('group_id')

    op.drop_table('django_celery_results_chordcounter')
    op.drop_table('user')
    with op.batch_alter_table('dvadmin_api_white_list', schema=None) as batch_op:
        batch_op.drop_index('dvadmin_api_white_list_creator_id_fd335789')

    op.drop_table('dvadmin_api_white_list')
    with op.batch_alter_table('django_session', schema=None) as batch_op:
        batch_op.drop_index('django_session_expire_date_a5c62663')

    op.drop_table('django_session')
    with op.batch_alter_table('token_blacklist_outstandingtoken', schema=None) as batch_op:
        batch_op.drop_index('token_blacklist_outstandingtoken_jti_hex_d9bdf6f7_uniq')

    op.drop_table('token_blacklist_outstandingtoken')
    with op.batch_alter_table('dvadmin_system_role', schema=None) as batch_op:
        batch_op.drop_index('dvadmin_system_role_creator_id_a89a9bc7')
        batch_op.drop_index('key')

    op.drop_table('dvadmin_system_role')
    op.drop_table('django_celery_beat_periodictasks')
    with op.batch_alter_table('dvadmin_system_users_user_permissions', schema=None) as batch_op:
        batch_op.drop_index('dvadmin_system_users_use_users_id_permission_id_24cd72ef_uniq')

    op.drop_table('dvadmin_system_users_user_permissions')
    with op.batch_alter_table('auth_group_permissions', schema=None) as batch_op:
        batch_op.drop_index('auth_group_permissions_group_id_permission_id_0cd325b0_uniq')

    op.drop_table('auth_group_permissions')
    with op.batch_alter_table('auth_group', schema=None) as batch_op:
        batch_op.drop_index('name')

    op.drop_table('auth_group')
    with op.batch_alter_table('dvadmin_system_dictionary', schema=None) as batch_op:
        batch_op.drop_index('dvadmin_system_dictionary_creator_id_d1b44b9d')
        batch_op.drop_index('dvadmin_system_dictionary_parent_id_4cceb110')

    op.drop_table('dvadmin_system_dictionary')
    with op.batch_alter_table('dvadmin_raw_data', schema=None) as batch_op:
        batch_op.drop_index('dvadmin_raw_data_creator_id_09d4c314')
        batch_op.drop_index('dvadmin_raw_data_is_deleted_20f693ea')

    op.drop_table('dvadmin_raw_data')
    with op.batch_alter_table('dvadmin_system_menu_button', schema=None) as batch_op:
        batch_op.drop_index('dvadmin_system_menu_button_creator_id_3df058f7')
        batch_op.drop_index('dvadmin_system_menu_button_menu_id_f6aafcd8')

    op.drop_table('dvadmin_system_menu_button')
    with op.batch_alter_table('dvadmin_system_users_post', schema=None) as batch_op:
        batch_op.drop_index('dvadmin_system_users_post_post_id_50054985')
        batch_op.drop_index('dvadmin_system_users_post_users_id_8ab2e760')
        batch_op.drop_index('dvadmin_system_users_post_users_id_post_id_41f83b22_uniq')

    op.drop_table('dvadmin_system_users_post')
    with op.batch_alter_table('dvadmin_system_role_menu', schema=None) as batch_op:
        batch_op.drop_index('dvadmin_system_role_menu_menu_id_7bbf1cb9')
        batch_op.drop_index('dvadmin_system_role_menu_role_id_dcc80258')
        batch_op.drop_index('dvadmin_system_role_menu_role_id_menu_id_06192289_uniq')

    op.drop_table('dvadmin_system_role_menu')
    with op.batch_alter_table('django_celery_beat_periodictask', schema=None) as batch_op:
        batch_op.drop_index('name')

    op.drop_table('django_celery_beat_periodictask')
    with op.batch_alter_table('dvadmin_tasks_dept', schema=None) as batch_op:
        batch_op.drop_index('dvadmin_tasks_dept_tasks_id_dept_id_206c1611_uniq')

    op.drop_table('dvadmin_tasks_dept')
    with op.batch_alter_table('dvadmin_system_menu', schema=None) as batch_op:
        batch_op.drop_index('dvadmin_system_menu_creator_id_430cdc1c')
        batch_op.drop_index('dvadmin_system_menu_parent_id_bc6f21bc')

    op.drop_table('dvadmin_system_menu')
    with op.batch_alter_table('dvadmin_system_operation_log', schema=None) as batch_op:
        batch_op.drop_index('dvadmin_system_operation_log_creator_id_0914479c')

    op.drop_table('dvadmin_system_operation_log')
    with op.batch_alter_table('token_blacklist_blacklistedtoken', schema=None) as batch_op:
        batch_op.drop_index('token_id')

    op.drop_table('token_blacklist_blacklistedtoken')
    with op.batch_alter_table('dvadmin_system_file_list', schema=None) as batch_op:
        batch_op.drop_index('dvadmin_system_file_list_creator_id_dec6acb5')

    op.drop_table('dvadmin_system_file_list')
    with op.batch_alter_table('dvadmin_system_users', schema=None) as batch_op:
        batch_op.drop_index('dvadmin_system_users_creator_id_28556713')
        batch_op.drop_index('dvadmin_system_users_dept_id_b56f71f6')
        batch_op.drop_index('employee_no')
        batch_op.drop_index('username')

    op.drop_table('dvadmin_system_users')
    with op.batch_alter_table('dvadmin_message_center', schema=None) as batch_op:
        batch_op.drop_index('dvadmin_message_center_creator_id_60e2080e')

    op.drop_table('dvadmin_message_center')
    with op.batch_alter_table('dvadmin_message_center_target_role', schema=None) as batch_op:
        batch_op.drop_index('dvadmin_message_center_t_messagecenter_id_role_id_f5a77970_uniq')
        batch_op.drop_index('dvadmin_message_center_target_role_messagecenter_id_41a7bd9d')
        batch_op.drop_index('dvadmin_message_center_target_role_role_id_661a61bb')

    op.drop_table('dvadmin_message_center_target_role')
    with op.batch_alter_table('dvadmin_system_area', schema=None) as batch_op:
        batch_op.drop_index('code')
        batch_op.drop_index('dvadmin_system_area_creator_id_a5046ac0')
        batch_op.drop_index('dvadmin_system_area_pcode_id_f9b21462')

    op.drop_table('dvadmin_system_area')
    with op.batch_alter_table('dvadmin_task_log', schema=None) as batch_op:
        batch_op.drop_index('dvadmin_task_log_creator_id_667a57d1')

    op.drop_table('dvadmin_task_log')
    with op.batch_alter_table('auth_permission', schema=None) as batch_op:
        batch_op.drop_index('auth_permission_content_type_id_codename_01ab375a_uniq')

    op.drop_table('auth_permission')
    op.drop_table('django_celery_beat_clockedschedule')
    with op.batch_alter_table('dvadmin_system_role_dept', schema=None) as batch_op:
        batch_op.drop_index('dvadmin_system_role_dept_dept_id_d719761c')
        batch_op.drop_index('dvadmin_system_role_dept_role_id_4f737c95')
        batch_op.drop_index('dvadmin_system_role_dept_role_id_dept_id_524d7fba_uniq')

    op.drop_table('dvadmin_system_role_dept')
    op.drop_table('django_migrations')
    with op.batch_alter_table('dvadmin_system_config', schema=None) as batch_op:
        batch_op.drop_index('dvadmin_system_config_creator_id_ba7fd60a')
        batch_op.drop_index('dvadmin_system_config_key_473a4f8d')
        batch_op.drop_index('dvadmin_system_config_key_parent_id_f8627867_uniq')
        batch_op.drop_index('dvadmin_system_config_parent_id_1ff841b5')

    op.drop_table('dvadmin_system_config')
    with op.batch_alter_table('django_celery_results_taskresult', schema=None) as batch_op:
        batch_op.drop_index('django_cele_date_cr_f04a50_idx')
        batch_op.drop_index('django_cele_date_do_f59aad_idx')
        batch_op.drop_index('django_cele_status_9b6201_idx')
        batch_op.drop_index('django_cele_task_na_08aec9_idx')
        batch_op.drop_index('django_cele_worker_d54dd8_idx')
        batch_op.drop_index('task_id')

    op.drop_table('django_celery_results_taskresult')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('django_celery_results_taskresult',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('task_id', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=False),
    sa.Column('status', mysql.VARCHAR(collation='utf8mb4_general_ci', length=50), nullable=False),
    sa.Column('content_type', mysql.VARCHAR(collation='utf8mb4_general_ci', length=128), nullable=False),
    sa.Column('content_encoding', mysql.VARCHAR(collation='utf8mb4_general_ci', length=64), nullable=False),
    sa.Column('result', mysql.LONGTEXT(collation='utf8mb4_general_ci'), nullable=True),
    sa.Column('date_done', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('traceback', mysql.LONGTEXT(collation='utf8mb4_general_ci'), nullable=True),
    sa.Column('meta', mysql.LONGTEXT(collation='utf8mb4_general_ci'), nullable=True),
    sa.Column('task_args', mysql.LONGTEXT(collation='utf8mb4_general_ci'), nullable=True),
    sa.Column('task_kwargs', mysql.LONGTEXT(collation='utf8mb4_general_ci'), nullable=True),
    sa.Column('task_name', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=True),
    sa.Column('worker', mysql.VARCHAR(collation='utf8mb4_general_ci', length=100), nullable=True),
    sa.Column('date_created', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('periodic_task_name', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('django_celery_results_taskresult', schema=None) as batch_op:
        batch_op.create_index('task_id', ['task_id'], unique=True)
        batch_op.create_index('django_cele_worker_d54dd8_idx', ['worker'], unique=False)
        batch_op.create_index('django_cele_task_na_08aec9_idx', ['task_name'], unique=False)
        batch_op.create_index('django_cele_status_9b6201_idx', ['status'], unique=False)
        batch_op.create_index('django_cele_date_do_f59aad_idx', ['date_done'], unique=False)
        batch_op.create_index('django_cele_date_cr_f04a50_idx', ['date_created'], unique=False)

    op.create_table('dvadmin_system_config',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('description', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=True),
    sa.Column('modifier', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=True),
    sa.Column('dept_belong_id', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=True),
    sa.Column('update_datetime', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('create_datetime', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('title', mysql.VARCHAR(collation='utf8mb4_general_ci', length=50), nullable=False),
    sa.Column('key', mysql.VARCHAR(collation='utf8mb4_general_ci', length=200), nullable=False),
    sa.Column('value', mysql.JSON(), nullable=True),
    sa.Column('sort', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('data_options', mysql.JSON(), nullable=True),
    sa.Column('form_item_type', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rule', mysql.JSON(), nullable=True),
    sa.Column('placeholder', mysql.VARCHAR(collation='utf8mb4_general_ci', length=100), nullable=True),
    sa.Column('setting', mysql.JSON(), nullable=True),
    sa.Column('creator_id', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('parent_id', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('dvadmin_system_config', schema=None) as batch_op:
        batch_op.create_index('dvadmin_system_config_parent_id_1ff841b5', ['parent_id'], unique=False)
        batch_op.create_index('dvadmin_system_config_key_parent_id_f8627867_uniq', ['key', 'parent_id'], unique=True)
        batch_op.create_index('dvadmin_system_config_key_473a4f8d', ['key'], unique=False)
        batch_op.create_index('dvadmin_system_config_creator_id_ba7fd60a', ['creator_id'], unique=False)

    op.create_table('django_migrations',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('app', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=False),
    sa.Column('applied', mysql.DATETIME(fsp=6), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('dvadmin_system_role_dept',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('role_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('dept_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('dvadmin_system_role_dept', schema=None) as batch_op:
        batch_op.create_index('dvadmin_system_role_dept_role_id_dept_id_524d7fba_uniq', ['role_id', 'dept_id'], unique=True)
        batch_op.create_index('dvadmin_system_role_dept_role_id_4f737c95', ['role_id'], unique=False)
        batch_op.create_index('dvadmin_system_role_dept_dept_id_d719761c', ['dept_id'], unique=False)

    op.create_table('django_celery_beat_clockedschedule',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('clocked_time', mysql.DATETIME(fsp=6), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('auth_permission',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=False),
    sa.Column('content_type_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('codename', mysql.VARCHAR(collation='utf8mb4_general_ci', length=100), nullable=False),
    sa.ForeignKeyConstraint(['content_type_id'], ['django_content_type.id'], name='auth_permission_content_type_id_2f476e4b_fk_django_co'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('auth_permission', schema=None) as batch_op:
        batch_op.create_index('auth_permission_content_type_id_codename_01ab375a_uniq', ['content_type_id', 'codename'], unique=True)

    op.create_table('dvadmin_task_log',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('description', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=True),
    sa.Column('modifier', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=True),
    sa.Column('dept_belong_id', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=True),
    sa.Column('serpapi_id', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=True),
    sa.Column('status', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('json_endpoint', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=True),
    sa.Column('google_url', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=True),
    sa.Column('raw_html_file', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=True),
    sa.Column('search_parameters', mysql.LONGTEXT(collation='utf8mb4_general_ci'), nullable=True),
    sa.Column('error_message', mysql.LONGTEXT(collation='utf8mb4_general_ci'), nullable=True),
    sa.Column('create_datetime', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('update_datetime', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('creator_id', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('task_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['dvadmin_tasks.id'], name='dvadmin_task_log_task_id_1f5c1240_fk_dvadmin_tasks_id'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('dvadmin_task_log', schema=None) as batch_op:
        batch_op.create_index('dvadmin_task_log_creator_id_667a57d1', ['creator_id'], unique=False)

    op.create_table('dvadmin_system_area',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('description', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=True),
    sa.Column('modifier', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=True),
    sa.Column('dept_belong_id', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=True),
    sa.Column('update_datetime', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('create_datetime', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('name', mysql.VARCHAR(collation='utf8mb4_general_ci', length=100), nullable=False),
    sa.Column('code', mysql.VARCHAR(collation='utf8mb4_general_ci', length=20), nullable=False),
    sa.Column('level', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('pinyin', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=False),
    sa.Column('initials', mysql.VARCHAR(collation='utf8mb4_general_ci', length=20), nullable=False),
    sa.Column('enable', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('creator_id', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('pcode_id', mysql.VARCHAR(collation='utf8mb4_general_ci', length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('dvadmin_system_area', schema=None) as batch_op:
        batch_op.create_index('dvadmin_system_area_pcode_id_f9b21462', ['pcode_id'], unique=False)
        batch_op.create_index('dvadmin_system_area_creator_id_a5046ac0', ['creator_id'], unique=False)
        batch_op.create_index('code', ['code'], unique=True)

    op.create_table('dvadmin_message_center_target_role',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('messagecenter_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('role_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('dvadmin_message_center_target_role', schema=None) as batch_op:
        batch_op.create_index('dvadmin_message_center_target_role_role_id_661a61bb', ['role_id'], unique=False)
        batch_op.create_index('dvadmin_message_center_target_role_messagecenter_id_41a7bd9d', ['messagecenter_id'], unique=False)
        batch_op.create_index('dvadmin_message_center_t_messagecenter_id_role_id_f5a77970_uniq', ['messagecenter_id', 'role_id'], unique=True)

    op.create_table('dvadmin_message_center',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('description', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=True),
    sa.Column('modifier', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=True),
    sa.Column('dept_belong_id', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=True),
    sa.Column('update_datetime', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('create_datetime', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('title', mysql.VARCHAR(collation='utf8mb4_general_ci', length=100), nullable=False),
    sa.Column('content', mysql.LONGTEXT(collation='utf8mb4_general_ci'), nullable=False),
    sa.Column('target_type', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('creator_id', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('dvadmin_message_center', schema=None) as batch_op:
        batch_op.create_index('dvadmin_message_center_creator_id_60e2080e', ['creator_id'], unique=False)

    op.create_table('dvadmin_system_users',
    sa.Column('password', mysql.VARCHAR(collation='utf8mb4_general_ci', length=128), nullable=False),
    sa.Column('last_login', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('is_superuser', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('first_name', mysql.VARCHAR(collation='utf8mb4_general_ci', length=150), nullable=False),
    sa.Column('last_name', mysql.VARCHAR(collation='utf8mb4_general_ci', length=150), nullable=False),
    sa.Column('is_staff', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('date_joined', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('description', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=True),
    sa.Column('modifier', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=True),
    sa.Column('dept_belong_id', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=True),
    sa.Column('update_datetime', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('create_datetime', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('username', mysql.VARCHAR(collation='utf8mb4_general_ci', length=150), nullable=False),
    sa.Column('employee_no', mysql.VARCHAR(collation='utf8mb4_general_ci', length=150), nullable=True),
    sa.Column('email', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=True),
    sa.Column('mobile', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=True),
    sa.Column('avatar', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=True),
    sa.Column('name', mysql.VARCHAR(collation='utf8mb4_general_ci', length=40), nullable=False),
    sa.Column('query_limit', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('used_limit', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('gender', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_type', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('last_token', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=True),
    sa.Column('creator_id', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('dept_id', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('dvadmin_system_users', schema=None) as batch_op:
        batch_op.create_index('username', ['username'], unique=True)
        batch_op.create_index('employee_no', ['employee_no'], unique=True)
        batch_op.create_index('dvadmin_system_users_dept_id_b56f71f6', ['dept_id'], unique=False)
        batch_op.create_index('dvadmin_system_users_creator_id_28556713', ['creator_id'], unique=False)

    op.create_table('dvadmin_system_file_list',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('description', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=True),
    sa.Column('modifier', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=True),
    sa.Column('dept_belong_id', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=True),
    sa.Column('update_datetime', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('create_datetime', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('name', mysql.VARCHAR(collation='utf8mb4_general_ci', length=200), nullable=True),
    sa.Column('url', mysql.VARCHAR(collation='utf8mb4_general_ci', length=100), nullable=True),
    sa.Column('file_url', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=False),
    sa.Column('engine', mysql.VARCHAR(collation='utf8mb4_general_ci', length=100), nullable=False),
    sa.Column('mime_type', mysql.VARCHAR(collation='utf8mb4_general_ci', length=100), nullable=False),
    sa.Column('size', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('md5sum', mysql.VARCHAR(collation='utf8mb4_general_ci', length=36), nullable=False),
    sa.Column('creator_id', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('dvadmin_system_file_list', schema=None) as batch_op:
        batch_op.create_index('dvadmin_system_file_list_creator_id_dec6acb5', ['creator_id'], unique=False)

    op.create_table('token_blacklist_blacklistedtoken',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('blacklisted_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('token_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['token_id'], ['token_blacklist_outstandingtoken.id'], name='token_blacklist_blacklistedtoken_token_id_3cc7fe56_fk'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('token_blacklist_blacklistedtoken', schema=None) as batch_op:
        batch_op.create_index('token_id', ['token_id'], unique=True)

    op.create_table('dvadmin_system_operation_log',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('description', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=True),
    sa.Column('modifier', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=True),
    sa.Column('dept_belong_id', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=True),
    sa.Column('update_datetime', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('create_datetime', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('request_modular', mysql.VARCHAR(collation='utf8mb4_general_ci', length=64), nullable=True),
    sa.Column('request_path', mysql.VARCHAR(collation='utf8mb4_general_ci', length=400), nullable=True),
    sa.Column('request_body', mysql.LONGTEXT(collation='utf8mb4_general_ci'), nullable=True),
    sa.Column('request_method', mysql.VARCHAR(collation='utf8mb4_general_ci', length=8), nullable=True),
    sa.Column('request_msg', mysql.LONGTEXT(collation='utf8mb4_general_ci'), nullable=True),
    sa.Column('request_ip', mysql.VARCHAR(collation='utf8mb4_general_ci', length=32), nullable=True),
    sa.Column('request_browser', mysql.VARCHAR(collation='utf8mb4_general_ci', length=64), nullable=True),
    sa.Column('response_code', mysql.VARCHAR(collation='utf8mb4_general_ci', length=32), nullable=True),
    sa.Column('request_os', mysql.VARCHAR(collation='utf8mb4_general_ci', length=64), nullable=True),
    sa.Column('json_result', mysql.LONGTEXT(collation='utf8mb4_general_ci'), nullable=True),
    sa.Column('status', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('creator_id', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('dvadmin_system_operation_log', schema=None) as batch_op:
        batch_op.create_index('dvadmin_system_operation_log_creator_id_0914479c', ['creator_id'], unique=False)

    op.create_table('dvadmin_system_menu',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('description', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=True),
    sa.Column('modifier', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=True),
    sa.Column('dept_belong_id', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=True),
    sa.Column('update_datetime', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('create_datetime', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('icon', mysql.VARCHAR(collation='utf8mb4_general_ci', length=64), nullable=True),
    sa.Column('name', mysql.VARCHAR(collation='utf8mb4_general_ci', length=64), nullable=False),
    sa.Column('sort', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_link', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('is_catalog', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('web_path', mysql.VARCHAR(collation='utf8mb4_general_ci', length=128), nullable=True),
    sa.Column('component', mysql.VARCHAR(collation='utf8mb4_general_ci', length=128), nullable=True),
    sa.Column('component_name', mysql.VARCHAR(collation='utf8mb4_general_ci', length=50), nullable=True),
    sa.Column('status', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('frame_out', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('cache', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('visible', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('remark', mysql.VARCHAR(collation='utf8mb4_general_ci', length=2000), nullable=True),
    sa.Column('creator_id', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('parent_id', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('dvadmin_system_menu', schema=None) as batch_op:
        batch_op.create_index('dvadmin_system_menu_parent_id_bc6f21bc', ['parent_id'], unique=False)
        batch_op.create_index('dvadmin_system_menu_creator_id_430cdc1c', ['creator_id'], unique=False)

    op.create_table('dvadmin_tasks_dept',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tasks_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('dept_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['dept_id'], ['dvadmin_system_dept.id'], name='dvadmin_tasks_dept_dept_id_3a0c9da2_fk_dvadmin_system_dept_id'),
    sa.ForeignKeyConstraint(['tasks_id'], ['dvadmin_tasks.id'], name='dvadmin_tasks_dept_tasks_id_9169021b_fk_dvadmin_tasks_id'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('dvadmin_tasks_dept', schema=None) as batch_op:
        batch_op.create_index('dvadmin_tasks_dept_tasks_id_dept_id_206c1611_uniq', ['tasks_id', 'dept_id'], unique=True)

    op.create_table('django_celery_beat_periodictask',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8mb4_general_ci', length=200), nullable=False),
    sa.Column('task', mysql.VARCHAR(collation='utf8mb4_general_ci', length=200), nullable=False),
    sa.Column('args', mysql.LONGTEXT(collation='utf8mb4_general_ci'), nullable=False),
    sa.Column('kwargs', mysql.LONGTEXT(collation='utf8mb4_general_ci'), nullable=False),
    sa.Column('queue', mysql.VARCHAR(collation='utf8mb4_general_ci', length=200), nullable=True),
    sa.Column('exchange', mysql.VARCHAR(collation='utf8mb4_general_ci', length=200), nullable=True),
    sa.Column('routing_key', mysql.VARCHAR(collation='utf8mb4_general_ci', length=200), nullable=True),
    sa.Column('expires', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('enabled', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('last_run_at', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('total_run_count', mysql.INTEGER(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('date_changed', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('description', mysql.LONGTEXT(collation='utf8mb4_general_ci'), nullable=False),
    sa.Column('crontab_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('interval_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('solar_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('one_off', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('start_time', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('priority', mysql.INTEGER(unsigned=True), autoincrement=False, nullable=True),
    sa.Column('headers', mysql.LONGTEXT(collation='utf8mb4_general_ci'), nullable=False),
    sa.Column('clocked_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('expire_seconds', mysql.INTEGER(unsigned=True), autoincrement=False, nullable=True),
    sa.CheckConstraint('(`expire_seconds` >= 0)', name='django_celery_beat_periodictask_chk_3'),
    sa.CheckConstraint('(`priority` >= 0)', name='django_celery_beat_periodictask_chk_2'),
    sa.CheckConstraint('(`total_run_count` >= 0)', name='django_celery_beat_periodictask_chk_1'),
    sa.ForeignKeyConstraint(['clocked_id'], ['django_celery_beat_clockedschedule.id'], name='django_celery_beat_p_clocked_id_47a69f82_fk_django_ce'),
    sa.ForeignKeyConstraint(['crontab_id'], ['django_celery_beat_crontabschedule.id'], name='django_celery_beat_p_crontab_id_d3cba168_fk_django_ce'),
    sa.ForeignKeyConstraint(['interval_id'], ['django_celery_beat_intervalschedule.id'], name='django_celery_beat_p_interval_id_a8ca27da_fk_django_ce'),
    sa.ForeignKeyConstraint(['solar_id'], ['django_celery_beat_solarschedule.id'], name='django_celery_beat_p_solar_id_a87ce72c_fk_django_ce'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('django_celery_beat_periodictask', schema=None) as batch_op:
        batch_op.create_index('name', ['name'], unique=True)

    op.create_table('dvadmin_system_role_menu',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('role_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('menu_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('dvadmin_system_role_menu', schema=None) as batch_op:
        batch_op.create_index('dvadmin_system_role_menu_role_id_menu_id_06192289_uniq', ['role_id', 'menu_id'], unique=True)
        batch_op.create_index('dvadmin_system_role_menu_role_id_dcc80258', ['role_id'], unique=False)
        batch_op.create_index('dvadmin_system_role_menu_menu_id_7bbf1cb9', ['menu_id'], unique=False)

    op.create_table('dvadmin_system_users_post',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('users_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('post_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('dvadmin_system_users_post', schema=None) as batch_op:
        batch_op.create_index('dvadmin_system_users_post_users_id_post_id_41f83b22_uniq', ['users_id', 'post_id'], unique=True)
        batch_op.create_index('dvadmin_system_users_post_users_id_8ab2e760', ['users_id'], unique=False)
        batch_op.create_index('dvadmin_system_users_post_post_id_50054985', ['post_id'], unique=False)

    op.create_table('dvadmin_system_menu_button',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('description', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=True),
    sa.Column('modifier', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=True),
    sa.Column('dept_belong_id', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=True),
    sa.Column('update_datetime', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('create_datetime', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('name', mysql.VARCHAR(collation='utf8mb4_general_ci', length=64), nullable=False),
    sa.Column('value', mysql.VARCHAR(collation='utf8mb4_general_ci', length=64), nullable=False),
    sa.Column('api', mysql.VARCHAR(collation='utf8mb4_general_ci', length=200), nullable=False),
    sa.Column('method', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('creator_id', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('menu_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('dvadmin_system_menu_button', schema=None) as batch_op:
        batch_op.create_index('dvadmin_system_menu_button_menu_id_f6aafcd8', ['menu_id'], unique=False)
        batch_op.create_index('dvadmin_system_menu_button_creator_id_3df058f7', ['creator_id'], unique=False)

    op.create_table('dvadmin_raw_data',
    sa.Column('is_deleted', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('description', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=True),
    sa.Column('modifier', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=True),
    sa.Column('dept_belong_id', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=True),
    sa.Column('update_datetime', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('create_datetime', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('title', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=False),
    sa.Column('link', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=False),
    sa.Column('source', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=False),
    sa.Column('datetime', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=False),
    sa.Column('snippet', mysql.LONGTEXT(collation='utf8mb4_general_ci'), nullable=False),
    sa.Column('content', mysql.LONGTEXT(collation='utf8mb4_general_ci'), nullable=False),
    sa.Column('image_url', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=False),
    sa.Column('creator_id', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('dvadmin_raw_data', schema=None) as batch_op:
        batch_op.create_index('dvadmin_raw_data_is_deleted_20f693ea', ['is_deleted'], unique=False)
        batch_op.create_index('dvadmin_raw_data_creator_id_09d4c314', ['creator_id'], unique=False)

    op.create_table('dvadmin_system_dictionary',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('description', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=True),
    sa.Column('modifier', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=True),
    sa.Column('dept_belong_id', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=True),
    sa.Column('update_datetime', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('create_datetime', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('label', mysql.VARCHAR(collation='utf8mb4_general_ci', length=100), nullable=True),
    sa.Column('value', mysql.VARCHAR(collation='utf8mb4_general_ci', length=200), nullable=True),
    sa.Column('type', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('color', mysql.VARCHAR(collation='utf8mb4_general_ci', length=20), nullable=True),
    sa.Column('is_value', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('status', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('sort', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('remark', mysql.VARCHAR(collation='utf8mb4_general_ci', length=2000), nullable=True),
    sa.Column('creator_id', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('parent_id', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('dvadmin_system_dictionary', schema=None) as batch_op:
        batch_op.create_index('dvadmin_system_dictionary_parent_id_4cceb110', ['parent_id'], unique=False)
        batch_op.create_index('dvadmin_system_dictionary_creator_id_d1b44b9d', ['creator_id'], unique=False)

    op.create_table('auth_group',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8mb4_general_ci', length=150), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('auth_group', schema=None) as batch_op:
        batch_op.create_index('name', ['name'], unique=True)

    op.create_table('auth_group_permissions',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('group_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('permission_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['auth_group.id'], name='auth_group_permissions_group_id_b120cbf9_fk_auth_group_id'),
    sa.ForeignKeyConstraint(['permission_id'], ['auth_permission.id'], name='auth_group_permissio_permission_id_84c5c92e_fk_auth_perm'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('auth_group_permissions', schema=None) as batch_op:
        batch_op.create_index('auth_group_permissions_group_id_permission_id_0cd325b0_uniq', ['group_id', 'permission_id'], unique=True)

    op.create_table('dvadmin_system_users_user_permissions',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('users_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('permission_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['auth_permission.id'], name='dvadmin_system_users_permission_id_c8ec58dc_fk_auth_perm'),
    sa.ForeignKeyConstraint(['users_id'], ['dvadmin_system_users.id'], name='dvadmin_system_users_users_id_fd3b0217_fk_dvadmin_s'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('dvadmin_system_users_user_permissions', schema=None) as batch_op:
        batch_op.create_index('dvadmin_system_users_use_users_id_permission_id_24cd72ef_uniq', ['users_id', 'permission_id'], unique=True)

    op.create_table('django_celery_beat_periodictasks',
    sa.Column('ident', mysql.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('last_update', mysql.DATETIME(fsp=6), nullable=False),
    sa.PrimaryKeyConstraint('ident'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('dvadmin_system_role',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('description', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=True),
    sa.Column('modifier', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=True),
    sa.Column('dept_belong_id', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=True),
    sa.Column('update_datetime', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('create_datetime', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('name', mysql.VARCHAR(collation='utf8mb4_general_ci', length=64), nullable=False),
    sa.Column('key', mysql.VARCHAR(collation='utf8mb4_general_ci', length=64), nullable=False),
    sa.Column('sort', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('admin', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('data_range', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('remark', mysql.LONGTEXT(collation='utf8mb4_general_ci'), nullable=True),
    sa.Column('creator_id', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('dvadmin_system_role', schema=None) as batch_op:
        batch_op.create_index('key', ['key'], unique=True)
        batch_op.create_index('dvadmin_system_role_creator_id_a89a9bc7', ['creator_id'], unique=False)

    op.create_table('token_blacklist_outstandingtoken',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('token', mysql.LONGTEXT(collation='utf8mb4_general_ci'), nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('expires_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('user_id', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('jti', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['dvadmin_system_users.id'], name='token_blacklist_outs_user_id_83bc629a_fk_dvadmin_s'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('token_blacklist_outstandingtoken', schema=None) as batch_op:
        batch_op.create_index('token_blacklist_outstandingtoken_jti_hex_d9bdf6f7_uniq', ['jti'], unique=True)

    op.create_table('django_session',
    sa.Column('session_key', mysql.VARCHAR(collation='utf8mb4_general_ci', length=40), nullable=False),
    sa.Column('session_data', mysql.LONGTEXT(collation='utf8mb4_general_ci'), nullable=False),
    sa.Column('expire_date', mysql.DATETIME(fsp=6), nullable=False),
    sa.PrimaryKeyConstraint('session_key'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('django_session', schema=None) as batch_op:
        batch_op.create_index('django_session_expire_date_a5c62663', ['expire_date'], unique=False)

    op.create_table('dvadmin_api_white_list',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('description', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=True),
    sa.Column('modifier', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=True),
    sa.Column('dept_belong_id', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=True),
    sa.Column('update_datetime', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('create_datetime', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('url', mysql.VARCHAR(collation='utf8mb4_general_ci', length=200), nullable=False),
    sa.Column('method', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('enable_datasource', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('creator_id', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('dvadmin_api_white_list', schema=None) as batch_op:
        batch_op.create_index('dvadmin_api_white_list_creator_id_fd335789', ['creator_id'], unique=False)

    op.create_table('user',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(collation='utf8mb4_general_ci', length=50), nullable=False),
    sa.Column('password', mysql.VARCHAR(collation='utf8mb4_general_ci', length=50), nullable=False),
    sa.Column('gender', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('django_celery_results_chordcounter',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('group_id', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=False),
    sa.Column('sub_tasks', mysql.LONGTEXT(collation='utf8mb4_general_ci'), nullable=False),
    sa.Column('count', mysql.INTEGER(unsigned=True), autoincrement=False, nullable=False),
    sa.CheckConstraint('(`count` >= 0)', name='django_celery_results_chordcounter_chk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('django_celery_results_chordcounter', schema=None) as batch_op:
        batch_op.create_index('group_id', ['group_id'], unique=True)

    op.create_table('dvadmin_message_center_target_dept',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('messagecenter_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('dept_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('dvadmin_message_center_target_dept', schema=None) as batch_op:
        batch_op.create_index('dvadmin_message_center_target_dept_messagecenter_id_69868c17', ['messagecenter_id'], unique=False)
        batch_op.create_index('dvadmin_message_center_target_dept_dept_id_616decc4', ['dept_id'], unique=False)
        batch_op.create_index('dvadmin_message_center_t_messagecenter_id_dept_id_d9fb0c77_uniq', ['messagecenter_id', 'dept_id'], unique=True)

    op.create_table('django_celery_beat_crontabschedule',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('minute', mysql.VARCHAR(collation='utf8mb4_general_ci', length=240), nullable=False),
    sa.Column('hour', mysql.VARCHAR(collation='utf8mb4_general_ci', length=96), nullable=False),
    sa.Column('day_of_week', mysql.VARCHAR(collation='utf8mb4_general_ci', length=64), nullable=False),
    sa.Column('day_of_month', mysql.VARCHAR(collation='utf8mb4_general_ci', length=124), nullable=False),
    sa.Column('month_of_year', mysql.VARCHAR(collation='utf8mb4_general_ci', length=64), nullable=False),
    sa.Column('timezone', mysql.VARCHAR(collation='utf8mb4_general_ci', length=63), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('django_content_type',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('app_label', mysql.VARCHAR(collation='utf8mb4_general_ci', length=100), nullable=False),
    sa.Column('model', mysql.VARCHAR(collation='utf8mb4_general_ci', length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('django_content_type', schema=None) as batch_op:
        batch_op.create_index('django_content_type_app_label_model_76bd3d3b_uniq', ['app_label', 'model'], unique=True)

    op.create_table('django_celery_results_groupresult',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('group_id', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=False),
    sa.Column('date_created', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('date_done', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('content_type', mysql.VARCHAR(collation='utf8mb4_general_ci', length=128), nullable=False),
    sa.Column('content_encoding', mysql.VARCHAR(collation='utf8mb4_general_ci', length=64), nullable=False),
    sa.Column('result', mysql.LONGTEXT(collation='utf8mb4_general_ci'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('django_celery_results_groupresult', schema=None) as batch_op:
        batch_op.create_index('group_id', ['group_id'], unique=True)
        batch_op.create_index('django_cele_date_do_caae0e_idx', ['date_done'], unique=False)
        batch_op.create_index('django_cele_date_cr_bd6c1d_idx', ['date_created'], unique=False)

    op.create_table('django_celery_beat_intervalschedule',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('every', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('period', mysql.VARCHAR(collation='utf8mb4_general_ci', length=24), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('dvadmin_message_center_target_user',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('description', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=True),
    sa.Column('modifier', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=True),
    sa.Column('dept_belong_id', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=True),
    sa.Column('update_datetime', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('create_datetime', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('is_read', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('creator_id', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('messagecenter_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('users_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('dvadmin_message_center_target_user', schema=None) as batch_op:
        batch_op.create_index('dvadmin_message_center_target_user_users_id_9ff81ff5', ['users_id'], unique=False)
        batch_op.create_index('dvadmin_message_center_target_user_messagecenter_id_54f35bf8', ['messagecenter_id'], unique=False)
        batch_op.create_index('dvadmin_message_center_target_user_creator_id_0a27a561', ['creator_id'], unique=False)

    op.create_table('dvadmin_system_login_log',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('description', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=True),
    sa.Column('modifier', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=True),
    sa.Column('dept_belong_id', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=True),
    sa.Column('update_datetime', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('create_datetime', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('username', mysql.VARCHAR(collation='utf8mb4_general_ci', length=150), nullable=True),
    sa.Column('ip', mysql.VARCHAR(collation='utf8mb4_general_ci', length=32), nullable=True),
    sa.Column('agent', mysql.LONGTEXT(collation='utf8mb4_general_ci'), nullable=True),
    sa.Column('browser', mysql.VARCHAR(collation='utf8mb4_general_ci', length=200), nullable=True),
    sa.Column('os', mysql.VARCHAR(collation='utf8mb4_general_ci', length=200), nullable=True),
    sa.Column('continent', mysql.VARCHAR(collation='utf8mb4_general_ci', length=50), nullable=True),
    sa.Column('country', mysql.VARCHAR(collation='utf8mb4_general_ci', length=50), nullable=True),
    sa.Column('province', mysql.VARCHAR(collation='utf8mb4_general_ci', length=50), nullable=True),
    sa.Column('city', mysql.VARCHAR(collation='utf8mb4_general_ci', length=50), nullable=True),
    sa.Column('district', mysql.VARCHAR(collation='utf8mb4_general_ci', length=50), nullable=True),
    sa.Column('isp', mysql.VARCHAR(collation='utf8mb4_general_ci', length=50), nullable=True),
    sa.Column('area_code', mysql.VARCHAR(collation='utf8mb4_general_ci', length=50), nullable=True),
    sa.Column('country_english', mysql.VARCHAR(collation='utf8mb4_general_ci', length=50), nullable=True),
    sa.Column('country_code', mysql.VARCHAR(collation='utf8mb4_general_ci', length=50), nullable=True),
    sa.Column('longitude', mysql.VARCHAR(collation='utf8mb4_general_ci', length=50), nullable=True),
    sa.Column('latitude', mysql.VARCHAR(collation='utf8mb4_general_ci', length=50), nullable=True),
    sa.Column('login_type', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('creator_id', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('dvadmin_system_login_log', schema=None) as batch_op:
        batch_op.create_index('dvadmin_system_login_log_creator_id_5f6dc165', ['creator_id'], unique=False)

    op.create_table('captcha_captchastore',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('challenge', mysql.VARCHAR(collation='utf8mb4_general_ci', length=32), nullable=False),
    sa.Column('response', mysql.VARCHAR(collation='utf8mb4_general_ci', length=32), nullable=False),
    sa.Column('hashkey', mysql.VARCHAR(collation='utf8mb4_general_ci', length=40), nullable=False),
    sa.Column('expiration', mysql.DATETIME(fsp=6), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('captcha_captchastore', schema=None) as batch_op:
        batch_op.create_index('hashkey', ['hashkey'], unique=True)

    op.create_table('dvadmin_system_users_role',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('users_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('role_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('dvadmin_system_users_role', schema=None) as batch_op:
        batch_op.create_index('dvadmin_system_users_role_users_id_role_id_02908e92_uniq', ['users_id', 'role_id'], unique=True)
        batch_op.create_index('dvadmin_system_users_role_users_id_a25207bc', ['users_id'], unique=False)
        batch_op.create_index('dvadmin_system_users_role_role_id_e37d9591', ['role_id'], unique=False)

    op.create_table('article',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', mysql.VARCHAR(collation='utf8mb4_general_ci', length=50), nullable=False),
    sa.Column('content', mysql.TEXT(collation='utf8mb4_general_ci'), nullable=False),
    sa.Column('author_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], name='article_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('dvadmin_task_result',
    sa.Column('is_deleted', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('description', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=True),
    sa.Column('modifier', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=True),
    sa.Column('dept_belong_id', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=True),
    sa.Column('update_datetime', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('create_datetime', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('title', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=False),
    sa.Column('link', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=False),
    sa.Column('source', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=False),
    sa.Column('datetime', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=False),
    sa.Column('snippet', mysql.LONGTEXT(collation='utf8mb4_general_ci'), nullable=False),
    sa.Column('content', mysql.LONGTEXT(collation='utf8mb4_general_ci'), nullable=False),
    sa.Column('image_url', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=False),
    sa.Column('creator_id', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('keyword_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('task_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['keyword_id'], ['dvadmin_keywords.id'], name='dvadmin_task_result_keyword_id_b4f75790_fk_dvadmin_keywords_id'),
    sa.ForeignKeyConstraint(['task_id'], ['dvadmin_tasks.id'], name='dvadmin_task_result_task_id_68fbac31_fk_dvadmin_tasks_id'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('dvadmin_task_result', schema=None) as batch_op:
        batch_op.create_index('dvadmin_task_result_is_deleted_af5ad10e', ['is_deleted'], unique=False)
        batch_op.create_index('dvadmin_task_result_creator_id_f7f8b173', ['creator_id'], unique=False)

    op.create_table('django_celery_beat_solarschedule',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('event', mysql.VARCHAR(collation='utf8mb4_general_ci', length=24), nullable=False),
    sa.Column('latitude', mysql.DECIMAL(precision=9, scale=6), nullable=False),
    sa.Column('longitude', mysql.DECIMAL(precision=9, scale=6), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('django_celery_beat_solarschedule', schema=None) as batch_op:
        batch_op.create_index('django_celery_beat_solar_event_latitude_longitude_ba64999a_uniq', ['event', 'latitude', 'longitude'], unique=True)

    op.create_table('dvadmin_system_role_permission',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('role_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('menubutton_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('dvadmin_system_role_permission', schema=None) as batch_op:
        batch_op.create_index('dvadmin_system_role_permission_role_id_bf988ad5', ['role_id'], unique=False)
        batch_op.create_index('dvadmin_system_role_permission_menubutton_id_7ba32ee0', ['menubutton_id'], unique=False)
        batch_op.create_index('dvadmin_system_role_perm_role_id_menubutton_id_46c1e3ca_uniq', ['role_id', 'menubutton_id'], unique=True)

    op.create_table('dvadmin_system_users_groups',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('users_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('group_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['auth_group.id'], name='dvadmin_system_users_groups_group_id_42e8a6dc_fk_auth_group_id'),
    sa.ForeignKeyConstraint(['users_id'], ['dvadmin_system_users.id'], name='dvadmin_system_users_users_id_f20fa5bc_fk_dvadmin_s'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('dvadmin_system_users_groups', schema=None) as batch_op:
        batch_op.create_index('dvadmin_system_users_groups_users_id_group_id_7460f482_uniq', ['users_id', 'group_id'], unique=True)

    op.create_table('dvadmin_system_dept',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('description', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=True),
    sa.Column('modifier', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=True),
    sa.Column('dept_belong_id', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=True),
    sa.Column('update_datetime', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('create_datetime', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('name', mysql.VARCHAR(collation='utf8mb4_general_ci', length=64), nullable=False),
    sa.Column('key', mysql.VARCHAR(collation='utf8mb4_general_ci', length=64), nullable=True),
    sa.Column('sort', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('owner', mysql.VARCHAR(collation='utf8mb4_general_ci', length=32), nullable=True),
    sa.Column('phone', mysql.VARCHAR(collation='utf8mb4_general_ci', length=32), nullable=True),
    sa.Column('email', mysql.VARCHAR(collation='utf8mb4_general_ci', length=32), nullable=True),
    sa.Column('status', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('expire_time', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('user_no', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('query_limit', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('used_limit', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('mail_notification', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('mail_sent_time', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('remark', mysql.LONGTEXT(collation='utf8mb4_general_ci'), nullable=True),
    sa.Column('creator_id', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('parent_id', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('dvadmin_system_dept', schema=None) as batch_op:
        batch_op.create_index('key', ['key'], unique=True)
        batch_op.create_index('dvadmin_system_dept_parent_id_0f9eb419', ['parent_id'], unique=False)
        batch_op.create_index('dvadmin_system_dept_creator_id_e69fd1ae', ['creator_id'], unique=False)

    op.create_table('dvadmin_system_post',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('description', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=True),
    sa.Column('modifier', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=True),
    sa.Column('dept_belong_id', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=True),
    sa.Column('update_datetime', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('create_datetime', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('name', mysql.VARCHAR(collation='utf8mb4_general_ci', length=64), nullable=False),
    sa.Column('code', mysql.VARCHAR(collation='utf8mb4_general_ci', length=32), nullable=False),
    sa.Column('sort', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('creator_id', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('dvadmin_system_post', schema=None) as batch_op:
        batch_op.create_index('dvadmin_system_post_creator_id_b5ef9351', ['creator_id'], unique=False)

    op.create_table('dvadmin_keywords',
    sa.Column('is_deleted', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('description', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=True),
    sa.Column('modifier', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=True),
    sa.Column('dept_belong_id', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=True),
    sa.Column('keywords', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=False),
    sa.Column('sort', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('create_datetime', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('update_datetime', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('creator_id', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('dvadmin_keywords', schema=None) as batch_op:
        batch_op.create_index('dvadmin_keywords_is_deleted_75748605', ['is_deleted'], unique=False)
        batch_op.create_index('dvadmin_keywords_creator_id_78641082', ['creator_id'], unique=False)

    op.create_table('dvadmin_tasks',
    sa.Column('is_deleted', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('description', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=True),
    sa.Column('modifier', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=True),
    sa.Column('dept_belong_id', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=True),
    sa.Column('update_datetime', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('create_datetime', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('title', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=True),
    sa.Column('sort', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('repeat', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('repeat_type', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('task_date', mysql.JSON(), nullable=True),
    sa.Column('task_week', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('task_time', mysql.TIME(fsp=6), nullable=True),
    sa.Column('filter', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('num_per_page', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('no_cache', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('location', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=True),
    sa.Column('gl', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=True),
    sa.Column('lr', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=True),
    sa.Column('safe', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=False),
    sa.Column('email_notification', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('email_delay_time', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('nfpr', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tbs', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=True),
    sa.Column('task_complete_datetime', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('creator_id', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('keyword_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['keyword_id'], ['dvadmin_keywords.id'], name='dvadmin_tasks_keyword_id_0c5fb2f8_fk_dvadmin_keywords_id'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('dvadmin_tasks', schema=None) as batch_op:
        batch_op.create_index('keyword_id', ['keyword_id'], unique=True)
        batch_op.create_index('dvadmin_tasks_is_deleted_acdeefcb', ['is_deleted'], unique=False)
        batch_op.create_index('dvadmin_tasks_creator_id_0c2ca68f', ['creator_id'], unique=False)

    op.drop_table('news')
    # ### end Alembic commands ###
